#include <Arduino.h>
#include "func.h"
#include "player.h"
#include "compass.h"
#include "distance.h"
#include "led.h"
#include "button.h"
#include "camera.h"
#include "dribbler.h"
#include "shooter.h"
#include "Grayscale.h"
#include "GoToCoordinate.h"
#include "bluetooth.h"
#include "goToBall.h"
#include "compoundEye.h"
#include "DFUltraTrig.h"
//button 1-6 = digital 30-35


void player();
void setMaxSpeed(int max);
void setCompassMax(int max);
void setMotorsDir(int dir1, int dir2, int dir3, int dir4);
void setupMotors();
void setupCamera();
void setSerialMonitor();
void setupCompass();

void setup() {
  //
//...................................................................................
//....................................tttttt.........................................
//....................................tttttt.........................................
//....................................tttttt.........................................
//....................................tttttt.........................................
//.....sssssssss........eeeeeeeee...ettttttttt.uuuuuu....uuuuuu...ppppp.ppppppp......
//...sssssssssssss....eeeeeeeeeeee..ettttttttttuuuuuu....uuuuuuu..ppppppppppppppp....
//..ssssssssssssss...eeeeeeeeeeeeee.ettttttttttuuuuuu....uuuuuuu..ppppppppppppppp....
//..sssssssssssssss..eeeeeeeeeeeeeeeettttttttttuuuuuu....uuuuuuu..pppppppppppppppp...
//..ssssss..sssssss.eeeeeeeeeeeeeeeeettttttttt.uuuuuu....uuuuuuu..ppppppppppppppppp..
//.ssssssss..ssssss.eeeeee....eeeeee..tttttt...uuuuuu....uuuuuuu..ppppppp...ppppppp..
//.ssssssssssss.....eeeeeeeeeeeeeeeee.tttttt...uuuuuu....uuuuuuu..pppppp....ppppppp..
//..sssssssssssss..seeeeeeeeeeeeeeeee.tttttt...uuuuuu....uuuuuuu..pppppp.....pppppp..
//..ssssssssssssss.seeeeeeeeeeeeeeeee.tttttt...uuuuuu....uuuuuuu..pppppp.....pppppp..
//...ssssssssssssssseeeeeeeeeeeeeeeee.tttttt...uuuuuu....uuuuuuu..pppppp.....pppppp..
//......sssssssssssseeeeeeeeeeeeeeee..tttttt...uuuuuu....uuuuuuu..pppppp....ppppppp..
//.ssssss..ssssssssseeeeee....eeeeee..tttttt...uuuuuuu...uuuuuuu..pppppp....ppppppp..
//.sssssss...ssssssseeeeeee...eeeeee..tttttt...uuuuuuu..uuuuuuuu..ppppppp..pppppppp..
//.ssssssssssssssss.eeeeeeeeeeeeeeee..tttttttt.uuuuuuuuuuuuuuuuu..pppppppppppppppp...
//..sssssssssssssss..eeeeeeeeeeeeeee..ttttttttt.uuuuuuuuuuuuuuuu..pppppppppppppppp...
//..ssssssssssssss....eeeeeeeeeeeee...ttttttttt.uuuuuuuuuuuuuuuu..ppppppppppppppp....
//...ssssssssssss......eeeeeeeeeee.....tttttttt..uuuuuuuuuuuuuuu..pppppppppppppp.....
//.....ssssssss..........eeeeeee.........ttttt.....uuuuu..........pppppp.ppppp.......
//................................................................pppppp.............
//................................................................pppppp.............
//................................................................pppppp.............
//................................................................pppppp.............
//................................................................pppppp.............
//................................................................pppppp.............
//...................................................................................
  // Serial.begin(9600);
  setSerialMonitor(); 
  setupDribbler();
  setBotNum(1);
  setupMotors();
  Serial.println("running basic setup...");
  setupKicker();
  setupCamera();
  Serial.println("entering setup loop");
  // setupDistance();
  setupCompass();
  setupButton();
  setUpBallPID();
  setupBluetooth();
  Serial.println("entering main loop");
  initSensors();
  eyeSetup();
  setupDefense();
  Serial.println("finished setting up whiteLine");

  



  //.................................................................
//..lllll..........................................................
//.llllll..........................................................
//.llllll..........................................................
//.llllll..........................................................
//.llllll..........................................................
//.llllll..........................................................
//.llllll.....oooooooooo.........oooooooooo.....ppppppppppppp......
//.llllll....ooooooooooooo......oooooooooooo....ppppppppppppppp....
//.llllll...ooooooooooooooo....oooooooooooooo...pppppppppppppppp...
//.llllll...ooooooooooooooo...oooooooooooooooo..pppppppppppppppp...
//.llllll..looooooo.oooooooo..oooooooooooooooo..ppppppppppppppppp..
//.llllll..loooooo...ooooooo.ooooooo....ooooooo.ppppppp...ppppppp..
//.llllll.llooooo.....oooooo.oooooo.....ooooooo.pppppp....ppppppp..
//.llllll.llooooo.....ooooooooooooo......oooooo.pppppp.....pppppp..
//.llllll.llooooo.....ooooooooooooo......oooooo.pppppp.....pppppp..
//.llllll.llooooo.....ooooooooooooo......oooooo.pppppp.....pppppp..
//.llllll.llooooo.....oooooo.oooooo.....ooooooo.pppppp.....pppppp..
//.llllll.llooooo.....oooooo.ooooooo....ooooooo.pppppp....ppppppp..
//.llllll..loooooo...ooooooo.oooooooo..oooooooo.ppppppp..pppppppp..
//.llllll..loooooooooooooooo..oooooooooooooooo..pppppppppppppppp...
//.llllll...ooooooooooooooo...oooooooooooooooo..pppppppppppppppp...
//.llllll....ooooooooooooo.....oooooooooooooo...ppppppppppppppp....
//.llllll.....ooooooooooo.......oooooooooooo....pppppppppppppp.....
//..............ooooooo...........oooooooo......pppppp.pppppp......
//..............................................pppppp.............
//..............................................pppppp.............
//..............................................pppppp.............
//..............................................pppppp.............
//..............................................pppppp.............
//..............................................pppppp.............
//.................................................................
  
}

void loop() {
  //some useful function to debug
  
  //while(1) setMotors(30,30,30,30);//uncomment to let the robot spin
  //while(1) setDribbler(ON,LOW);//uncomment to let the dribbler spin
  //..........................................................................................
  //....................lllll.................................................................
  //...................pllllll................................................................
  //...................pllllll................................................................
  //...................pllllll................................................................
  //...................pllllll................................................................
  //...................pllllll................................................................
  //.ppppppppppppp.....pllllll....aaaaaaaaaa...aayyyy.....yyyyyy....eeeeeeeee.....rrrrr.rrrr..
  //.ppppppppppppppp...pllllll...aaaaaaaaaaaa..aayyyyy....yyyyyy...eeeeeeeeeee....rrrrrrrrrr..
  //.pppppppppppppppp..pllllll..aaaaaaaaaaaaaa.aayyyyy...yyyyyyy.yeeeeeeeeeeeee...rrrrrrrrrr..
  //.pppppppppppppppp..pllllll..aaaaaaaaaaaaaaaaayyyyy...yyyyyyy.yeeeeeeeeeeeeee..rrrrrrrrrr..
  //.ppppppppppppppppp.pllllll.laaaaaaaaaaaaaaa.ayyyyy...yyyyyy.yyeeeeeeeeeeeeee..rrrrrrrrrr..
  //.ppppppp...ppppppp.pllllll.laaaaa...aaaaaaa.ayyyyyy..yyyyyy.yyeeeee...eeeeeee.rrrrrrrr....
  //.pppppp....ppppppp.pllllll..aaaaaaaaaaaaaaa.ayyyyyy.yyyyyyy.yyeeeeeeeeeeeeeee.rrrrrr......
  //.pppppp.....pppppp.pllllll...aaaaaaaaaaaaaa..yyyyyy.yyyyyy..yyeeeeeeeeeeeeeee.rrrrrr......
  //.pppppp.....pppppp.pllllll..aaaaaaaaaaaaaaa..yyyyyyyyyyyyy..yyeeeeeeeeeeeeeee.rrrrrr......
  //.pppppp.....pppppp.pllllll.laaaaaaaaaaaaaaa...yyyyyyyyyyyy..yyeeeeeeeeeeeeeee.rrrrrr......
  //.pppppp.....pppppp.pllllll.laaaaaaaa.aaaaaa...yyyyyyyyyyy...yyeeeeeeeeeeeeeee.rrrrrr......
  //.pppppp....ppppppp.pllllll.laaaaa...aaaaaaa...yyyyyyyyyyy...yyeeee.....eeeee..rrrrrr......
  //.ppppppp..pppppppp.pllllll.laaaaa...aaaaaaa....yyyyyyyyy....yyeeeee...eeeeeee.rrrrrr......
  //.pppppppppppppppp..pllllll.laaaaaaaaaaaaaaa....yyyyyyyyy.....yeeeeeeeeeeeeee..rrrrrr......
  //.pppppppppppppppp..pllllll.laaaaaaaaaaaaaaa....yyyyyyyyy.....yeeeeeeeeeeeeee..rrrrrr......
  //.ppppppppppppppp...pllllll.laaaaaaaaaaaaaaa.....yyyyyyy.......eeeeeeeeeeeee...rrrrrr......
  //.pppppppppppppp....pllllll..aaaaaaaaaaaaaaaa....yyyyyyy........eeeeeeeeeee....rrrrrr......
  //.pppppp.pppppp................aaaaaa............yyyyyyy..........eeeeeee..................
  //.pppppp.........................................yyyyyy....................................
  //.pppppp......................................yyyyyyyyy....................................
  //.pppppp......................................yyyyyyyyy....................................
  //.pppppp......................................yyyyyyyy.....................................
  //.pppppp......................................yyyyyyy......................................
  //.pppppp......................................yyyyyy.......................................
  //..........................................................................................
  //player run only once
  //setMotors(20,20,20,20);
  // while(1){
  //   setMotors(10, 10, 20, 20);
  // }
  player();
 

}
